// Generated by gencpp from file planner_and_control/Encoder.msg
// DO NOT EDIT!


#ifndef PLANNER_AND_CONTROL_MESSAGE_ENCODER_H
#define PLANNER_AND_CONTROL_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_and_control
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : left(0)
    , right(0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int32_t _left_type;
  _left_type left;

   typedef int32_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::planner_and_control::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_and_control::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::planner_and_control::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::planner_and_control::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::planner_and_control::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_and_control::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_and_control::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_and_control::Encoder_<ContainerAllocator1> & lhs, const ::planner_and_control::Encoder_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_and_control::Encoder_<ContainerAllocator1> & lhs, const ::planner_and_control::Encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_and_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_and_control::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "febc810ab9cc360ca3f47fcee4f2ba71";
  }

  static const char* value(const ::planner_and_control::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfebc810ab9cc360cULL;
  static const uint64_t static_value2 = 0xa3f47fcee4f2ba71ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_and_control::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_and_control/Encoder";
  }

  static const char* value(const ::planner_and_control::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_and_control::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 left\n"
"int32 right\n"
;
  }

  static const char* value(const ::planner_and_control::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_and_control::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_and_control::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_and_control::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_AND_CONTROL_MESSAGE_ENCODER_H
