// Generated by gencpp from file planner_and_control/Obj.msg
// DO NOT EDIT!


#ifndef PLANNER_AND_CONTROL_MESSAGE_OBJ_H
#define PLANNER_AND_CONTROL_MESSAGE_OBJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_and_control
{
template <class ContainerAllocator>
struct Obj_
{
  typedef Obj_<ContainerAllocator> Type;

  Obj_()
    : x()
    , y()
    , r()  {
    }
  Obj_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , r(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::planner_and_control::Obj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_and_control::Obj_<ContainerAllocator> const> ConstPtr;

}; // struct Obj_

typedef ::planner_and_control::Obj_<std::allocator<void> > Obj;

typedef boost::shared_ptr< ::planner_and_control::Obj > ObjPtr;
typedef boost::shared_ptr< ::planner_and_control::Obj const> ObjConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_and_control::Obj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_and_control::Obj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_and_control::Obj_<ContainerAllocator1> & lhs, const ::planner_and_control::Obj_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.r == rhs.r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_and_control::Obj_<ContainerAllocator1> & lhs, const ::planner_and_control::Obj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_and_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Obj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Obj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Obj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Obj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Obj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Obj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_and_control::Obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cc8151f0e156e549859bb17a6e74a08";
  }

  static const char* value(const ::planner_and_control::Obj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cc8151f0e156e54ULL;
  static const uint64_t static_value2 = 0x9859bb17a6e74a08ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_and_control::Obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_and_control/Obj";
  }

  static const char* value(const ::planner_and_control::Obj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_and_control::Obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x\n"
"float64[] y\n"
"float64[] r\n"
;
  }

  static const char* value(const ::planner_and_control::Obj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_and_control::Obj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_and_control::Obj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_and_control::Obj_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "r[]" << std::endl;
    for (size_t i = 0; i < v.r.size(); ++i)
    {
      s << indent << "  r[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.r[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_AND_CONTROL_MESSAGE_OBJ_H
