// Generated by gencpp from file semi_final_pkg/gigacha.msg
// DO NOT EDIT!


#ifndef SEMI_FINAL_PKG_MESSAGE_GIGACHA_H
#define SEMI_FINAL_PKG_MESSAGE_GIGACHA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace semi_final_pkg
{
template <class ContainerAllocator>
struct gigacha_
{
  typedef gigacha_<ContainerAllocator> Type;

  gigacha_()
    {
    }
  gigacha_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::semi_final_pkg::gigacha_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::semi_final_pkg::gigacha_<ContainerAllocator> const> ConstPtr;

}; // struct gigacha_

typedef ::semi_final_pkg::gigacha_<std::allocator<void> > gigacha;

typedef boost::shared_ptr< ::semi_final_pkg::gigacha > gigachaPtr;
typedef boost::shared_ptr< ::semi_final_pkg::gigacha const> gigachaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::semi_final_pkg::gigacha_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::semi_final_pkg::gigacha_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace semi_final_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::semi_final_pkg::gigacha_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::semi_final_pkg::gigacha_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semi_final_pkg::gigacha_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::semi_final_pkg::gigacha_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semi_final_pkg::gigacha_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::semi_final_pkg::gigacha_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::semi_final_pkg::gigacha_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::semi_final_pkg::gigacha_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::semi_final_pkg::gigacha_<ContainerAllocator> >
{
  static const char* value()
  {
    return "semi_final_pkg/gigacha";
  }

  static const char* value(const ::semi_final_pkg::gigacha_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::semi_final_pkg::gigacha_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::semi_final_pkg::gigacha_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::semi_final_pkg::gigacha_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gigacha_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::semi_final_pkg::gigacha_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::semi_final_pkg::gigacha_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SEMI_FINAL_PKG_MESSAGE_GIGACHA_H
