// Generated by gencpp from file local_pkg/Displacement.msg
// DO NOT EDIT!


#ifndef LOCAL_PKG_MESSAGE_DISPLACEMENT_H
#define LOCAL_PKG_MESSAGE_DISPLACEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_pkg
{
template <class ContainerAllocator>
struct Displacement_
{
  typedef Displacement_<ContainerAllocator> Type;

  Displacement_()
    : left(0)
    , right(0)  {
    }
  Displacement_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int32_t _left_type;
  _left_type left;

   typedef int32_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::local_pkg::Displacement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_pkg::Displacement_<ContainerAllocator> const> ConstPtr;

}; // struct Displacement_

typedef ::local_pkg::Displacement_<std::allocator<void> > Displacement;

typedef boost::shared_ptr< ::local_pkg::Displacement > DisplacementPtr;
typedef boost::shared_ptr< ::local_pkg::Displacement const> DisplacementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_pkg::Displacement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_pkg::Displacement_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_pkg::Displacement_<ContainerAllocator1> & lhs, const ::local_pkg::Displacement_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_pkg::Displacement_<ContainerAllocator1> & lhs, const ::local_pkg::Displacement_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::local_pkg::Displacement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_pkg::Displacement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_pkg::Displacement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_pkg::Displacement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_pkg::Displacement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_pkg::Displacement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_pkg::Displacement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "febc810ab9cc360ca3f47fcee4f2ba71";
  }

  static const char* value(const ::local_pkg::Displacement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfebc810ab9cc360cULL;
  static const uint64_t static_value2 = 0xa3f47fcee4f2ba71ULL;
};

template<class ContainerAllocator>
struct DataType< ::local_pkg::Displacement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_pkg/Displacement";
  }

  static const char* value(const ::local_pkg::Displacement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_pkg::Displacement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 left\n"
"int32 right\n"
;
  }

  static const char* value(const ::local_pkg::Displacement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_pkg::Displacement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Displacement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_pkg::Displacement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_pkg::Displacement_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_PKG_MESSAGE_DISPLACEMENT_H
