# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner_and_control/Gngga.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Gngga(genpy.Message):
  _md5sum = "63e398a035d41ac999d8966a3c9d2faa"
  _type = "planner_and_control/Gngga"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 latitude
float64 longitude

float32 quality_indicator # 0 - fix not available, 1 - GPS fix, 2 - Differential GPS fix
float32 noise
float32 satellite
"""
  __slots__ = ['latitude','longitude','quality_indicator','noise','satellite']
  _slot_types = ['float64','float64','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,quality_indicator,noise,satellite

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Gngga, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.quality_indicator is None:
        self.quality_indicator = 0.
      if self.noise is None:
        self.noise = 0.
      if self.satellite is None:
        self.satellite = 0.
    else:
      self.latitude = 0.
      self.longitude = 0.
      self.quality_indicator = 0.
      self.noise = 0.
      self.satellite = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d3f().pack(_x.latitude, _x.longitude, _x.quality_indicator, _x.noise, _x.satellite))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.latitude, _x.longitude, _x.quality_indicator, _x.noise, _x.satellite,) = _get_struct_2d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d3f().pack(_x.latitude, _x.longitude, _x.quality_indicator, _x.noise, _x.satellite))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.latitude, _x.longitude, _x.quality_indicator, _x.noise, _x.satellite,) = _get_struct_2d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d3f = None
def _get_struct_2d3f():
    global _struct_2d3f
    if _struct_2d3f is None:
        _struct_2d3f = struct.Struct("<2d3f")
    return _struct_2d3f
